import { ReactNode } from "react";
import { Layout } from "../components/Layout";
import "../styles/index.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
